Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-chinese and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-chinese and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
--- Logging error ---
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "load_data_cls.py", line 113, in <module>
    log.logger.info (train_df.shape, test_df.shape, val_df.shape)
Message: (32546, 3)
Arguments: ((4532, 3), (8137, 3))
--- Logging error ---
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "load_data_cls.py", line 113, in <module>
    log.logger.info (train_df.shape, test_df.shape, val_df.shape)
Message: (32546, 3)
Arguments: ((4532, 3), (8137, 3))
2023-10-08 04:09:34,827 - load_data_cls.py[line:118] - INFO: DataLoader loading success
Simbert不能正常使用，除非你安装：bert4keras、tensorflow ，为了安装快捷，没有默认安装.... No module named 'bert4keras'
